{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Scraping\n",
    "Está função entra no Goolge Escolar e coleta por pesquisador, todos os artigos com seus respectivos autores, retornando uma lista com os titulos e autores."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "from selenium import webdriver\n",
    "from selenium.webdriver.common.keys import Keys\n",
    "from selenium.webdriver.support.ui import WebDriverWait\n",
    "from bs4 import BeautifulSoup\n",
    "import urllib.request\n",
    "import nbconvert\n",
    "import pandas as pd\n",
    "import time"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "def scrape(author_name):\n",
    "    site = \"http://scholar.google.com.br/\"\n",
    "    autor = author_name\n",
    "    \n",
    "    driver = webdriver.Chrome()\n",
    "    driver.get(site)\n",
    "    driver.implicitly_wait(100)\n",
    "    \n",
    "    entrada_autor = driver.find_element_by_id(\"gs_hdr_tsi\")\n",
    "    entrada_autor.send_keys(autor)\n",
    "    clicar = driver.find_element_by_id('gs_hdr_tsb')\n",
    "    clicar.click()\n",
    "    \n",
    "    continue_link = driver.find_element_by_link_text(autor)\n",
    "    continue_link.click()\n",
    "    \n",
    "    mostrar_mais = driver.find_element_by_id('gsc_bpf_more')\n",
    "    x = mostrar_mais.get_property('disabled')==False \n",
    "\n",
    "    while x:\n",
    "        mostrar_mais.click()\n",
    "        time.sleep(2)\n",
    "        x = mostrar_mais.get_property('disabled')==False\n",
    "\n",
    "    html = BeautifulSoup(driver.page_source)\n",
    "\n",
    "    tabela = html.find('table',{'id':'gsc_a_t'})\n",
    "    papers = []\n",
    "    trabalhos = tabela.find_all('td',{\"class\":'gsc_a_t'})\n",
    "    for trabalhos in tabela.find_all('td',{\"class\":'gsc_a_t'}):\n",
    "        titulo = trabalhos.find('a')\n",
    "        titulo = titulo.contents[0]\n",
    "        autores = trabalhos.find('div',{'class':'gs_gray'})\n",
    "        autores = autores.contents[0]\n",
    "        autores = autores.split(',')    \n",
    "        for i in autores:\n",
    "            autores = i.strip()            \n",
    "        if autores[-1]=='...':\n",
    "            autores.pop()\n",
    "        papers.append({'title':titulo,'authors':autores})\n",
    "\n",
    "    driver.quit()\n",
    "    return papers\n",
    "    \n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[{'title': 'D3: Data-Driven Documents', 'authors': 'J Heer'},\n",
       " {'title': 'Prefuse: a toolkit for interactive information visualization',\n",
       "  'authors': 'JA Landay'},\n",
       " {'title': 'Vizster: Visualizing online social networks', 'authors': 'D Boyd'},\n",
       " {'title': 'Narrative visualization: Telling stories with data',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Crowdsourcing graphical perception: using mechanical turk to assess visualization design',\n",
       "  'authors': 'M Bostock'},\n",
       " {'title': 'Interactive dynamics for visual analysis',\n",
       "  'authors': 'B Shneiderman'},\n",
       " {'title': 'A tour through the visualization zoo.', 'authors': 'V Ogievetsky'},\n",
       " {'title': 'Animated transitions in statistical data graphics',\n",
       "  'authors': 'G Robertson'},\n",
       " {'title': 'Profiles as conversation: Networked identity performance on Friendster',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Wrangler: Interactive visual specification of data transformation scripts',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Protovis: A graphical toolkit for visualization',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Design considerations for collaborative visual analytics',\n",
       "  'authors': 'M Agrawala'},\n",
       " {'title': 'Software design patterns for information visualization',\n",
       "  'authors': 'M Agrawala'},\n",
       " {'title': 'imMens: Real-time visual querying of big data',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Graphical histories for visualization: Supporting analysis, communication, and evaluation',\n",
       "  'authors': 'M Agrawala'},\n",
       " {'title': 'Voyagers and voyeurs: supporting asynchronous collaborative information visualization',\n",
       "  'authors': 'M Wattenberg'},\n",
       " {'title': 'Enterprise data analysis and visualization: An interview study',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Sizing the horizon: the effects of chart size and layering on the graphical perception of time series visualizations',\n",
       "  'authors': 'M Agrawala'},\n",
       " {'title': 'Termite: Visualization techniques for assessing textual topic models',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Scented widgets: Improving navigation cues with embedded visualizations',\n",
       "  'authors': 'M Agrawala'},\n",
       " {'title': 'Research directions in data wrangling: Visualizations and transformations for usable and credible data',\n",
       "  'authors': '...'},\n",
       " {'title': 'WebQuilt: A proxy-based approach to remote web usability testing',\n",
       "  'authors': 'JA Landay'},\n",
       " {'title': 'Interpretation and trust: Designing model-driven visualizations for text analysis',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Voyager: Exploratory analysis via faceted browsing of visualization recommendations',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'The effects of interactive latency on exploratory visual analysis',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'WebQuilt: a framework for capturing and visualizing the web experience',\n",
       "  'authors': 'JA Landay'},\n",
       " {'title': 'Profiler: Integrated statistical analysis and visualization for data quality assessment',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'The efficacy of human post-editing for language translation',\n",
       "  'authors': 'CD Manning'},\n",
       " {'title': 'Vega-lite: A grammar of interactive graphics',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Divided edge bundling for directional network data',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Creation and collaboration: Engaging new audiences for information visualization',\n",
       "  'authors': 'P Isenberg'},\n",
       " {'title': 'Voyagers and voyeurs: Supporting asynchronous collaborative visualization',\n",
       "  'authors': 'M Wattenberg'},\n",
       " {'title': 'Separating the swarm: categorization methods for user sessions on the web',\n",
       "  'authors': 'EH Chi'},\n",
       " {'title': 'Momento: support for situated ubicomp experimentation',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Identification of web user traffic composition using multi-modal clustering and information scent',\n",
       "  'authors': 'EH Chi'},\n",
       " {'title': 'DOITrees revisited: scalable, space-constrained visualization of hierarchical data',\n",
       "  'authors': 'SK Card'},\n",
       " {'title': 'Does binding of synesthetic color to the evoking grapheme require attention?',\n",
       "  'authors': 'L Robertson'},\n",
       " {'title': 'Color naming models for color selection, image editing and palette design',\n",
       "  'authors': 'M Stone'},\n",
       " {'title': 'Revision: Automated classification, analysis and redesign of chart images',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'CommentSpace: structured support for collaborative visual analysis',\n",
       "  'authors': 'M Agrawala'},\n",
       " {'title': 'Strategies for crowdsourcing social data analysis',\n",
       "  'authors': 'M Agrawala'},\n",
       " {'title': 'Lyra: An interactive visualization design environment',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Declarative language design for interactive visualization',\n",
       "  'authors': 'M Bostock'},\n",
       " {'title': 'Selecting Semantically-Resonant Colors for Data Visualization',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Perceptual guidelines for creating rectangular treemaps',\n",
       "  'authors': 'M Agrawala'},\n",
       " {'title': 'LumberJack: Intelligent discovery and analysis of web user traffic composition',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'A demonstration of the BigDAWG polystore system',\n",
       "  'authors': '...'},\n",
       " {'title': 'Topic Model Diagnostics: Assessing Domain Relevance via Topical Alignment',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Time tree: Exploring time changing hierarchies',\n",
       "  'authors': 'JW Bodnar'},\n",
       " {'title': 'Reactive vega: A streaming dataflow architecture for declarative interactive visualization',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Balancing exertion experiences', 'authors': 'J Heer'},\n",
       " {'title': 'Tracing genealogical data with timenets', 'authors': 'J Heer'},\n",
       " {'title': 'Orion: A system for modeling, transformation and visualization of multidimensional heterogeneous networks',\n",
       "  'authors': 'A Perer'},\n",
       " {'title': 'Probabilistic color-by-numbers: Suggesting pattern colorizations using factor graphs',\n",
       "  'authors': 'P Hanrahan'},\n",
       " {'title': 'Identifying medical terms in patient-authored text: a crowdsourcing-based approach',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Differentiating language usage through topic models',\n",
       "  'authors': 'D Jurafsky'},\n",
       " {'title': 'Wideband displays: mitigating multiple monitor seams',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': '“Without the clutter of unimportant words”: Descriptive keyphrases for text visualization',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Mining the structure of user activity using cluster stability',\n",
       "  'authors': 'EH Chi'},\n",
       " {'title': 'Learning perceptual kernels for visualization design',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'All friends are not equal: Using weights in social graphs to improve search',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Interactive analysis of big data', 'authors': 'S Kandel'},\n",
       " {'title': 'Authoring narrative visualizations with ellipsis',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Muse: Reviving memories using email archives',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Generalized selection via interactive query relaxation',\n",
       "  'authors': 'W Willett'},\n",
       " {'title': 'Voyager 2: Augmenting visual analysis with partial view specifications',\n",
       "  'authors': '...'},\n",
       " {'title': 'Peripheral paced respiration: influencing user physiology during information work',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Proactive wrangling: mixed-initiative end-user programming of data transformation scripts',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'liquid: Context-aware distributed queries', 'authors': 'JI Hong'},\n",
       " {'title': 'What did they do? understanding clickstreams with the WebQuilt visualization system',\n",
       "  'authors': 'T Matthews'},\n",
       " {'title': 'Predictive Interaction for Data Transformation.',\n",
       "  'authors': 'S Kandel'},\n",
       " {'title': 'Groups without tears: mining social topologies from email',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Visualizing collaboration and influence in the open-source software community',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': \"Beyond weber's law: A second look at ranking visualizations of correlation\",\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Declarative interaction design for data visualization',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Forum77: An analysis of an online health forum dedicated to addiction recovery',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Graphprism: compact visualization of network structure',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Visual embedding: A model for visualization', 'authors': 'J Heer'},\n",
       " {'title': 'Human effort and machine learnability in computer aided translation',\n",
       "  'authors': 'CD Manning'},\n",
       " {'title': 'Colony life history and lifetime reproductive success of red harvester ant colonies',\n",
       "  'authors': 'DM Gordon'},\n",
       " {'title': 'Method, apparatus, and program product for visualizing tree structured information',\n",
       "  'authors': 'SK Card'},\n",
       " {'title': 'Predictive Translation Memory: A mixed-initiative system for human language translation',\n",
       "  'authors': 'CD Manning'},\n",
       " {'title': 'Induced lexico-syntactic patterns improve information extraction from online medical forums',\n",
       "  'authors': 'CD Manning'},\n",
       " {'title': 'The software architect', 'authors': 'MR McBride'},\n",
       " {'title': 'A taxonomy of tools that support the fluent and flexible use of visualizations',\n",
       "  'authors': 'C Park'},\n",
       " {'title': 'Seeing the invisible', 'authors': 'P Khooshabeh'},\n",
       " {'title': 'Formalizing visualization design knowledge as constraints: Actionable and extensible models in Draco',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Reverse‐Engineering Visualizations: Recovering Visual Encodings from Chart Images',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Refinery: Visual exploration of large, heterogeneous networks through associative browsing',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'TopicCheck: Interactive alignment for assessing topic model stability',\n",
       "  'authors': '...'},\n",
       " {'title': 'Presiding over accidents: system direction of human action',\n",
       "  'authors': 'J Mankoff'},\n",
       " {'title': 'BodyDiagrams: improving communication of pain symptoms through drawing',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Systems and methods for identifying user types using multi-modal clustering and information scent',\n",
       "  'authors': 'PLT Pirolli'},\n",
       " {'title': 'Socializing visualization', 'authors': 'J Heer'},\n",
       " {'title': 'Towards a general-purpose query language for visualization recommendation',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Parting crowds: Characterizing divergent interpretations in crowdsourced annotation tasks',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Data collection', 'authors': 'G Nelson'},\n",
       " {'title': 'Surprise! Bayesian weighting for de-biasing thematic maps',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'What Did They Do? Understanding Clickstreams with the WebQuilt Visualization System',\n",
       "  'authors': 'T Matthews'},\n",
       " {'title': 'Prefuse: a software framework for interactive information visualization',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Visualizing the republic of letters', 'authors': 'J Heer'},\n",
       " {'title': 'Active capture: automatic direction for automatic movies',\n",
       "  'authors': 'A Ramírez'},\n",
       " {'title': 'Graphscape: A model for automated reasoning about visualization similarity and sequencing',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Generating personalized spatial analogies for distances and areas',\n",
       "  'authors': 'M Agrawala'},\n",
       " {'title': 'Information visualization', 'authors': 'S Robert'},\n",
       " {'title': 'Computer-assisted content analysis: Topic models for exploring multiple subjective interpretations',\n",
       "  'authors': '...'},\n",
       " {'title': 'Assessing effects of task and data distribution on the effectiveness of visual encodings',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Supporting asynchronous collaboration for interactive visualization',\n",
       "  'authors': 'JM Heer'},\n",
       " {'title': 'Augmenting code with in situ visualizations to aid program understanding',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Somewhere over the rainbow: An empirical assessment of quantitative colormaps',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Undergraduate conceptions of the engineering design process: Assessing the impact of a human-centered design course',\n",
       "  'authors': 'AM Agogino'},\n",
       " {'title': 'Point, talk, and publish: Visualisation and the web',\n",
       "  'authors': 'M Agrawala'},\n",
       " {'title': 'Data visualization', 'authors': 'S Few'},\n",
       " {'title': 'Systems and methods for clustering user sessions using multi-modal information including proximal cue information',\n",
       "  'authors': 'EH Chi'},\n",
       " {'title': 'Interactive analysis of word vector embeddings',\n",
       "  'authors': 'M Gleicher'},\n",
       " {'title': 'Document exploration with topic modeling: Designing interactive visualizations to support effective analysis workflows',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Data visualization and social data analysis',\n",
       "  'authors': 'JM Hellerstein'},\n",
       " {'title': 'Position statement: The case for a visualization performance benchmark',\n",
       "  'authors': 'M Stonebraker'},\n",
       " {'title': 'Extracting and retargeting color mappings from bitmap images of visualizations',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Regression by eye: Estimating trends in bivariate visualizations',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Natural language translation at the intersection of AI and HCI',\n",
       "  'authors': 'CD Manning'},\n",
       " {'title': 'Perfopticon: Visual query analysis for distributed databases',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Systems and methods for the estimation of user interest in graph theoretic structures',\n",
       "  'authors': 'SK Card'},\n",
       " {'title': 'Wideband visual interfaces: Sensemaking on multiple monitors',\n",
       "  'authors': 'C Royer'},\n",
       " {'title': 'D3 data-driven documents', 'authors': 'J Bostock'},\n",
       " {'title': 'Value-suppressing uncertainty palettes', 'authors': 'J Heer'},\n",
       " {'title': 'Black hat visualization', 'authors': 'J Heer'},\n",
       " {'title': 'Processing Email Archives in Special Collections.',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'System and method for redistributing interest in a hierarchical data structure representation',\n",
       "  'authors': 'SK Card'},\n",
       " {'title': 'Agency plus automation: Designing artificial intelligence into interactive systems',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Idyll: A Markup Language for Authoring and Publishing Interactive Articles on the Web.',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Visual debugging techniques for reactive data visualization',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'invis: Exploring high-dimensional RNA sequences from in vitro selection',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Topic models and the cultural sciences', 'authors': 'P Bogdanov'},\n",
       " {'title': 'Large-scale examination of academic publications using statistical models',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'An algorithm and analysis of social topologies from email and photo tags',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Altair: Interactive Statistical Visualizations for Python.',\n",
       "  'authors': '...'},\n",
       " {'title': 'IEEE Transactions on Visualization and Computer Graphics',\n",
       "  'authors': '...'},\n",
       " {'title': 'SetCoLa: High‐Level Constraints for Graph Layout',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Principles of data wrangling: Practical techniques for data preparation',\n",
       "  'authors': 'C Carreras'},\n",
       " {'title': 'Data collection by the people, for the people',\n",
       "  'authors': 'J Pierce'},\n",
       " {'title': 'Social data analysis workshop', 'authors': 'M Agrawala'},\n",
       " {'title': 'All together now: visualizing local and remote actors of localized activity',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Self-Service Data Preparation: Research to Practice.',\n",
       "  'authors': 'S Kandel'},\n",
       " {'title': 'The VERP Explorer: a tool for exploring eye movements of visual-cognitive tasks using recurrence plots',\n",
       "  'authors': 'SK Card'},\n",
       " {'title': 'Seeing the invisible', 'authors': 'P Khooshabeh'},\n",
       " {'title': 'Capturing and analyzing the web experience', 'authors': 'J Heer'},\n",
       " {'title': 'Beyond heuristics: Learning visualization design',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Designing a prototype interface for visual communication of pain',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Systems and methods for identifying user types using multi-modal clustering and information scent',\n",
       "  'authors': 'P Pirolli'},\n",
       " {'title': 'Efficient user interest estimation in fisheye views',\n",
       "  'authors': 'SK Card'},\n",
       " {'title': 'CFGExplorer: Designing a Visual Control Flow Analytics System around Basic Program Analysis Operations',\n",
       "  'authors': 'KE Isaacs'},\n",
       " {'title': 'Uncertainty footprint: visualization of nonuniform behavior of iterative algorithms applied to 4D cell tracking',\n",
       "  'authors': 'C Hansen'},\n",
       " {'title': 'Lyra: An Interactive Visualization Design Environment',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Many people, many eyes: aggregating influences of visual perception on user interface design',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Visualization Evaluation of the Masses, by the Masses, and for the Masses',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Voyagers and voyeurs: supporting social data analysis',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'The High Cost of Free Services: Problems with Surveillance Capitalism and Possible Alternatives for IT Infrastructure',\n",
       "  'authors': 'V Wulf'},\n",
       " {'title': 'Extracting visual encodings from map chart images with color-encoded scalar values',\n",
       "  'authors': 'J Poco'},\n",
       " {'title': 'Reverse-Engineering Visualizations: Recovering Visual Encodings from Chart Images',\n",
       "  'authors': 'J van Wijk'},\n",
       " {'title': 'Dynamic Client-Server Optimization for Scalable Interactive Visualization on the Web',\n",
       "  'authors': 'B Howe'},\n",
       " {'title': 'Local Decision Pitfalls in Interactive Machine Learning: An Investigation into Feature Selection in Sentiment Analysis',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Characterizing Exploratory Visual Analysis: A Literature Review and Evaluation of Analytic Provenance in Tableau',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Latent Space Cartography: Visual Analysis of Vector Space Embeddings',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Capture & Analysis of Active Reading Behaviors for Interactive Articles on the Web',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Designing Animated Transitions to Convey Aggregate Operations',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Falcon: Balancing Interactive Latency and Resolution Sensitivity for Scalable Linked Visualizations',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'The partnership on AI', 'authors': 'J Heer'},\n",
       " {'title': 'System and method for identifying fields in a file using examples in the file received from a user',\n",
       "  'authors': 'SP Kandel'},\n",
       " {'title': 'The 2017 Visualization Technical Achievement Award',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Front Matter Preface', 'authors': 'J van Wijk'},\n",
       " {'title': 'EuroVis 2017: Frontmatter', 'authors': 'J van Wijk'},\n",
       " {'title': 'System and method for annotation of data visualizations',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Proceedings of the Workshop on Interactive Language Learning, Visualization, and Interfaces',\n",
       "  'authors': 'P Koehn'},\n",
       " {'title': 'IEEE VISUAL ANALYTICS SCIENCE & TECHNOLOGY CONFERENCE, IEEE INFORMATION VISUALIZATION CONFERENCE, AND IEEE SCIENTIFIC VISUALIZATION CONFERENCE',\n",
       "  'authors': '...'},\n",
       " {'title': 'HCOMP-13 Organization', 'authors': 'E Horvitz'},\n",
       " {'title': 'Chan, Peter', 'authors': 'J Heer'},\n",
       " {'title': 'An Algorithm and Analysis of Social Topologies from Email and Photo Tags',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'An Algorithm and Analysis of Social Topologies from Email and Photo Tags',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'The Design of Sense. us', 'authors': 'J Heer'},\n",
       " {'title': 'Doubly linked visual discussions for data visualization',\n",
       "  'authors': 'MM Wattenberg'},\n",
       " {'title': 'Readings Covered', 'authors': 'A Anand'},\n",
       " {'title': 'WEBKDD 2002-Mining Web Data for Discovering Usage Patterns and Profiles: 4th International Workshop, Edmonton, Canada, July 23, 2002. Revised Papers',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Criterion Functions for Document Clustering.', 'authors': '...'},\n",
       " {'title': 'Exploratory data analysis', 'authors': 'J Heer'},\n",
       " {'title': 'Interactive Data Analysis', 'authors': 'J Heer'},\n",
       " {'title': 'Color Names Across Languages: Salient Colors and Term Translation in Multilingual Color Naming Models',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Visualizing Attention in Sequence-to-Sequence Summarization Models',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'LATEX Author Guidelines for EUROGRAPHICS Proceedings Manuscripts',\n",
       "  'authors': 'J van Wijk'},\n",
       " {'title': 'Final Project Proposal', 'authors': 'J Heer'},\n",
       " {'title': 'Visualizing Expanded Query Results', 'authors': 'T Ropinski'},\n",
       " {'title': 'Communication & Collaboration', 'authors': 'J Heer'},\n",
       " {'title': 'A Visual Inspection of Online Health Communities',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Computational Visualization Interpretation', 'authors': 'FF Li'},\n",
       " {'title': '“Without the Clutter of Unimportant Words”: Modeling How People Choose Descriptive Keyphrases',\n",
       "  'authors': 'CD Manning'},\n",
       " {'title': 'Assessing Effects of Task and Data Distribution on the Effectiveness of Visual Encodings',\n",
       "  'authors': 'T Ropinski'},\n",
       " {'title': 'Reapplication of SetCoLa Specifications for Biological Networks',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'Towards User-Centered Active Learning Algorithms–Supplemental Materials–',\n",
       "  'authors': 'T Ropinski'},\n",
       " {'title': 'Data-Parallel Hashing Techniques for GPU Architectures',\n",
       "  'authors': 'T Ropinski'},\n",
       " {'title': 'Rosson, Mary B./Carroll, John M.(2009): Sce', 'authors': '...'},\n",
       " {'title': 'Driving Interactive Graph Exploration Using 0-Dimensional Persistent Homology Features',\n",
       "  'authors': 'T Ropinski'},\n",
       " {'title': 'VAST Steering Committee', 'authors': '...'},\n",
       " {'title': 'Measuring Symmetry in Drawings of Graphs',\n",
       "  'authors': 'J van Wijk'},\n",
       " {'title': 'Global Feature Tracking and Similarity Estimation in Time-Dependent Scalar Fields',\n",
       "  'authors': 'J van Wijk'},\n",
       " {'title': 'Finding a Clear Path: Structuring Strategies for Visualization Sequences',\n",
       "  'authors': 'J van Wijk'},\n",
       " {'title': 'Design Critiques', 'authors': 'M Cusumano-Towner'},\n",
       " {'title': 'Exploring Dimensionality Reductions with Forward and Backward Projections',\n",
       "  'authors': 'J van Wijk'},\n",
       " {'title': 'Symposium Committee', 'authors': '...'},\n",
       " {'title': 'The Value of Visualization', 'authors': 'J Heer'},\n",
       " {'title': 'CSE512:: 30 Jan 2014', 'authors': 'J Heer'},\n",
       " {'title': 'VIS Conference Committee', 'authors': '...'},\n",
       " {'title': 'Topic Model Diagnostics: Assessing Domain Relevance via Topical Alignment (Supplementary Materials)',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'VIS Conference Committee', 'authors': '...'},\n",
       " {'title': 'Visual Embedding: A Model for Visualization!',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'prefuse.org', 'authors': 'J Heer'},\n",
       " {'title': 'matthewt@ seattleu. edu', 'authors': 'JA Landay'},\n",
       " {'title': 'SPECIAL ISSUE DOES BINDING OF SYNESTHETIC COLOR TO THE EVOKING GRAPHEME REQUIRE ATTENTION?',\n",
       "  'authors': 'L Robertson'},\n",
       " {'title': 'Evaluating Visualizations to Unearth Behavior and Insight',\n",
       "  'authors': 'J Heer'},\n",
       " {'title': 'VisWeek conference committee', 'authors': '...'},\n",
       " {'title': 'The Changing Dynamics of Scientific Collaborations',\n",
       "  'authors': 'C Silva'}]"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "papers = scrape('Jeffrey Heer')\n",
    "papers"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
